version: 0.0.{build}
pull_requests:
  do_not_increment_build_number: true
configuration: Release
before_build:
- nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: TorrentManager\packages\Tools.InnoSetup.5.5.6\tools\iscc TorrentManager.iss
artifacts:
- path: TorrentManager\Bin\Release\
deploy:
- provider: GitHub
  release: MK-v0.0.3
  auth_token:
    secure: dxXnDldxYhUSIpOtmipHvoDe77ApzWSAgwlaxo0QWlA5ACBgb2OJNSLyFFTIIQGP
  on:
    branch: master
    configuration: Release
    appveyor_repo_tag: true
